apiVersion: v1
kind: Service
metadata:
  name: elmerrosarioamazonspringer
  namespace: rosario-azure-dev
spec:
  type: LoadBalancer
  selector:
    app: elmerrosarioamazonspringer
  ports:
    - port: 80
      targetPort: 8080